version: "3"

services:
  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - /home/ubuntu/html:/usr/share/nginx/html
      - /home/ubuntu/nginx.conf:/etc/nginx/nginx.conf
    privileged: true  

  mysql:
    image: mysql:latest
    ports:
    - 3306:3306
    environment:
    - MYSQL_ROOT_PASSWORD=51522Zzwlwlbb@
    volumes:
    - /home/ubuntu/dockerData/mysql/data:/var/lib/mysql
    - /home/ubuntu/dockerData/mysql/log:/var/log/mysql

  redis:
    image: redis:3.0.5

  service-system:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8800:8800
    depends_on:
      - mysql
      - redis
